#cloud-config
package_upgrade: true
hostname: ${hostname}
fqdn: ${hostname}.${domain}
write_files:
  - content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && \
      while ! curl --output /dev/null --silent --head --fail http://$1; do sleep 2 && echo -n .; done;
      exit $?
    path: /opt/bin/wupiao
    permissions: '0755'
  - content: |
      #!/bin/bash
      HOSTIP=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
      MLD=$$(echo ${domain} | cut -d"." -f1)
      TLD=$$(echo ${domain} | cut -d"." -f2)
      # Disable resolv.conf management by dhclient
      sed -i -e '/PEERDNS=/ s/=.*/=\"no\"/' /etc/sysconfig/network-scripts/ifcfg-eth0

      cat > /etc/sysconfig/network <<EOF
      NETWORKING=yes
      NOZEROCONF=yes
      DNS1=${nameservers}
      SEARCH=${domain}
      EOF

      echo "My hostname is: ${hostname}.${domain}, IP: $${HOSTIP}"
      echo "Registering in SkyDNS instance: ${nameservers} after etcd became up"
      /opt/bin/wupiao ${nameservers}:4001/v2/machines
      echo "Calling http://${nameservers}:4001/v2/keys/skydns/$${TLD}/$${MLD}/${hostname}"
      curl --silent -XPUT http://${nameservers}:4001/v2/keys/skydns/$${TLD}/$${MLD}/${hostname} -d value={\"host\":\"$${HOSTIP}\"}
    path: /var/lib/cloud/scripts/per-boot/setup_dns.sh
    owner: root:root
    permissions: 0755
  - content: |
      # Generated by Terraform, will be overwritten on reboot
      nameserver ${nameservers}
      search ${domain}
    path: /etc/resolv.conf
    owner: root:root
    permissions: 0544
